<?php
/**
 * ═══════════════════════════════════════════════════
 *  sitemap.php — Technoplus.io
 *  Sitemap XML dynamique — généré depuis la base de données
 *  Conforme : https://www.sitemaps.org/protocol.html
 * ═══════════════════════════════════════════════════
 */

// ─── Configuration ────────────────────────────────────────────────────────────
define('SITE_URL', 'https://technoplus.io');
define('SITEMAP_CACHE_FILE', __DIR__ . '/sitemap_cache.xml');
define('SITEMAP_CACHE_TTL', 3600 * 6); // 6 heures

// ─── Servir depuis le cache si disponible ─────────────────────────────────────
if (file_exists(SITEMAP_CACHE_FILE)
    && (time() - filemtime(SITEMAP_CACHE_FILE)) < SITEMAP_CACHE_TTL)
{
    header('Content-Type: application/xml; charset=UTF-8');
    header('X-Sitemap-Cache: HIT');
    readfile(SITEMAP_CACHE_FILE);
    exit;
}

// ─── Connexion BDD ────────────────────────────────────────────────────────────
require_once __DIR__ . '/include.php';

// Désactiver le mode strict pour les requêtes (éviter les exceptions sur colonnes manquantes)
mysqli_report(MYSQLI_REPORT_OFF);

// ─── Construction du sitemap ──────────────────────────────────────────────────
$today = date('Y-m-d');
$urls  = [];

// ── 1. Pages statiques ────────────────────────────────────────────────────────
$staticPages = [
    ['loc' => '/',              'priority' => '1.00', 'changefreq' => 'daily'],
    ['loc' => '/contact',       'priority' => '0.70', 'changefreq' => 'monthly'],
    ['loc' => '/applications',  'priority' => '0.70', 'changefreq' => 'monthly'],
];
foreach ($staticPages as $page) {
    $urls[] = [
        'loc'        => SITE_URL . $page['loc'],
        'lastmod'    => $today,
        'changefreq' => $page['changefreq'],
        'priority'   => $page['priority'],
    ];
}

// ── 2. Catégories principales (site_menu) ─────────────────────────────────────
$reqMenu   = "SELECT `link`, `datecreation`
              FROM `site_menu`
              WHERE `etat` = '1' AND `link` != '' AND `link` != 'accueil'
              ORDER BY `ordre` ASC";
$resMenu   = @mysqli_query($connexion, $reqMenu);
if ($resMenu) {
    while ($row = mysqli_fetch_assoc($resMenu)) {
        $lastmod = !empty($row['datecreation']) ? date('Y-m-d', (int)$row['datecreation']) : $today;
        $urls[]  = [
            'loc'        => SITE_URL . '/boutique/' . htmlspecialchars($row['link'], ENT_XML1, 'UTF-8') . '/',
            'lastmod'    => $lastmod,
            'changefreq' => 'weekly',
            'priority'   => '0.80',
        ];
    }
}

// ── 3. Produits ───────────────────────────────────────────────────────────────
$reqProd = "SELECT `link`, `datecreation`
            FROM `produits`
            WHERE `etat` = '1' AND `link` != ''
            ORDER BY `id` DESC
            LIMIT 50000";
$resProd = @mysqli_query($connexion, $reqProd);
if ($resProd) {
    while ($row = mysqli_fetch_assoc($resProd)) {
        $lastmod  = !empty($row['datecreation']) ? date('Y-m-d', (int)$row['datecreation']) : $today;
        $prodSlug = htmlspecialchars($row['link'], ENT_XML1, 'UTF-8');
        $urls[] = [
            'loc'        => SITE_URL . '/produit/' . $prodSlug . '/',
            'lastmod'    => $lastmod,
            'changefreq' => 'weekly',
            'priority'   => '0.90',
        ];
    }
}

// ── 4. Marques ────────────────────────────────────────────────────────────────
$reqMarque = "SELECT `link`, `datecreation` FROM `marques` WHERE `etat` = '1' AND `link` != '' ORDER BY `raison` ASC";
$resMarque = @mysqli_query($connexion, $reqMarque);
if ($resMarque) {
    while ($row = mysqli_fetch_assoc($resMarque)) {
        $lastmod = !empty($row['datecreation']) ? date('Y-m-d', (int)$row['datecreation']) : $today;
        $urls[]  = [
            'loc'        => SITE_URL . '/marque/' . htmlspecialchars($row['link'], ENT_XML1, 'UTF-8') . '/',
            'lastmod'    => $lastmod,
            'changefreq' => 'monthly',
            'priority'   => '0.65',
        ];
    }
}

// ─── Génération du XML ────────────────────────────────────────────────────────
$xml  = '<?xml version="1.0" encoding="UTF-8"?>' . "\n";
$xml .= '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"' . "\n";
$xml .= '        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"' . "\n";
$xml .= '        xsi:schemaLocation="http://www.sitemaps.org/schemas/sitemap/0.9' . "\n";
$xml .= '              http://www.sitemaps.org/schemas/sitemap/0.9/sitemap.xsd">' . "\n";
$xml .= '<!-- Generated by sitemap.php — Technoplus.io — ' . date('Y-m-d H:i:s') . ' -->' . "\n";

foreach ($urls as $url) {
    $xml .= "  <url>\n";
    $xml .= "    <loc>" . $url['loc'] . "</loc>\n";
    $xml .= "    <lastmod>" . $url['lastmod'] . "</lastmod>\n";
    $xml .= "    <changefreq>" . $url['changefreq'] . "</changefreq>\n";
    $xml .= "    <priority>" . $url['priority'] . "</priority>\n";
    $xml .= "  </url>\n";
}

$xml .= '</urlset>';

// ─── Sauvegarde dans le cache ─────────────────────────────────────────────────
file_put_contents(SITEMAP_CACHE_FILE, $xml);

// ─── Envoi au navigateur / crawler ───────────────────────────────────────────
header('Content-Type: application/xml; charset=UTF-8');
header('X-Sitemap-Cache: MISS');
echo $xml;
